# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-color: #2e2e2e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, -20, 421, 131))
        self.frame.setStyleSheet("background-color: #738e67;\n"
"border: 2px;\n"
"border-radius: 50;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(80, 50, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0px;")
        self.label.setObjectName("label")
        self.input_str = QtWidgets.QLineEdit(self.centralwidget)
        self.input_str.setGeometry(QtCore.QRect(40, 140, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.input_str.setFont(font)
        self.input_str.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.input_str.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_str.setStyleSheet("background-color: #828282;\n"
"border: 3px solid #75896c;\n"
"border-radius: 20;\n"
"color: white;")
        self.input_str.setText("")
        self.input_str.setAlignment(QtCore.Qt.AlignCenter)
        self.input_str.setObjectName("input_str")
        self.input_num = QtWidgets.QLineEdit(self.centralwidget)
        self.input_num.setGeometry(QtCore.QRect(40, 220, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.input_num.setFont(font)
        self.input_num.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.input_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_num.setStyleSheet("background-color: #828282;\n"
"border: 3px solid #75896c;\n"
"border-radius: 20;\n"
"color: white;")
        self.input_num.setText("")
        self.input_num.setAlignment(QtCore.Qt.AlignCenter)
        self.input_num.setObjectName("input_num")
        self.output_str = QtWidgets.QLineEdit(self.centralwidget)
        self.output_str.setGeometry(QtCore.QRect(40, 300, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.output_str.setFont(font)
        self.output_str.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.output_str.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output_str.setStyleSheet("background-color: #828282;\n"
"border: 3px solid #75896c;\n"
"border-radius: 20;\n"
"color: white;")
        self.output_str.setText("")
        self.output_str.setAlignment(QtCore.Qt.AlignCenter)
        self.output_str.setObjectName("output_str")
        self.output_num = QtWidgets.QLineEdit(self.centralwidget)
        self.output_num.setGeometry(QtCore.QRect(40, 380, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.output_num.setFont(font)
        self.output_num.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.output_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.output_num.setStyleSheet("background-color: #828282;\n"
"border: 3px solid #75896c;\n"
"border-radius: 20;\n"
"color: white;")
        self.output_num.setText("")
        self.output_num.setAlignment(QtCore.Qt.AlignCenter)
        self.output_num.setObjectName("output_num")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 460, 321, 61))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: #828282;\n"
"border: 3px solid #75896c;\n"
"border-radius: 20;\n"
"color: white;")
        self.pushButton.setObjectName("pushButton")
        self.frame.raise_()
        self.input_str.raise_()
        self.input_num.raise_()
        self.output_str.raise_()
        self.output_num.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Перевод валют</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Конвертировать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
